### PR TITLE
feat: allow override of ca-certificates.crt

### PR DESCRIPTION
**Pull request by papanito**
Relates to #93, Implements #82

### CODE REVIEW

**Comment by papanito** [comment]
@lkysow can you have a look at this PR?

**Review by lkysow — APPROVED** [review]

**Comment by papanito** [comment]
Thanks a lot!

**Comment by papanito** [comment]
@lkysow Could you create a new release, containing my change? Would really appreciate it

**Comment by zbialik** [comment]
I could only get this to work if my Secret was generated having the `key=ca-certificates.crt`

Otherwise, I got an error:

`Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/var/lib/kubelet/pods/xxxxx/volume-subpaths/additional-trust-certs/atlantis/4" to rootfs at "/etc/ssl/certs/ca-certificates.crt" caused: mount through procfd: not a directory: unknown`

I believe this is because the `kubelet` assumes `/etc/ssl/certs/ca-certificates.crt` is a **directory** if the subpath doesn't match the filename designated in the Secret key... or something like that.

If this is the case, maybe this should be documented or perhaps enforced another way? Ideally, we'd like to be able to add custom CA's and have those appended to the ones already provided out-the-box without using an `initContainer` or building a custom image.

**Comment by papanito** [comment]
> If this is the case, maybe this should be documented

I can do that

> Ideally, we'd like to be able to add custom CA's and have those appended to the ones already provided out-the-box without using an initContainer or building a custom image.

Yeah this was my first thought, but if you add your certs with a configmap, you would have to run `update-ca-certificates`, which you cannot to with the user of Atlantis image.
My assumption was - as this is my setup - internal self-signed cerificates are only signed by the internal CA, so all other root ca's are irrelevant

**Pull request merged**
