### PR TITLE
fix: don't define resources

### PR DESCRIPTION
**Pull request by rissson**
## what

Remove cpu limits from the atlantis container

## why

Atlantis simply dies on simple tasks like `terraform init` with the current configuration.

## tests

- [x] I have tested my changes by running them in production.

## references

https://home.robusta.dev/blog/stop-using-cpu-limits

### CODE REVIEW

**Review by nitrocode — DISMISSED** [review]

**Comment by GenPage** [comment]
@jseiser The github action will not handle it. It will need a bump.

**Comment by GenPage** [comment]
The lint check fixes now catches a missing version bump

**Review by GMartinez-Sisti — APPROVED** [review]
LGTM

**Comment by rissson** [comment]
Updated as required.

**Review by GMartinez-Sisti — APPROVED** [review]

**Comment by rissson** [comment]
Maintainers have write access to this branch.

**Comment by jseiser** [comment]
We enabled parallel plans, and now we are hitting this same problem.  a MR is created and atlantis dies.

**Comment by jamengual** [comment]
@rissson can you please bump the version? usually, the user does this instead of us

**Review by jamengual — APPROVED** [review]

**Pull request merged**
