### PR TITLE
Revert Security Context Change

### PR DESCRIPTION
**Pull request by jamengual**
reverting #21 

more information here : https://github.com/runatlantis/helm-charts/issues/14

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
LGTM

**Comment by johanneswuerbach** [comment]
I just tried to install 4.0.4 on a GKE cluster and got:

```
docker-entrypoint.sh: detected /atlantis-data wrong filesystem permissions
currently owned by root:atlantis, changing to atlantis:atlantis...
chown: /atlantis-data/lost+found: Operation not permitted
chown: /atlantis-data/lost+found: Operation not permitted
chown: /atlantis-data: Operation not permitted
chown: /atlantis-data: Operation not permitted
```

Install 4.0.3 works without issues 🤔

**Comment by tekumara** [comment]
Same problem here with helm chart 4.0.4 and ghcr.io/runatlantis/atlantis:v0.19.4:
```
docker-entrypoint.sh: detected /atlantis-data wrong filesystem permissions
currently owned by root:atlantis, changing to atlantis:atlantis...
chown: /atlantis-data/lost+found: Operation not permitted
chown: /atlantis-data/lost+found: Operation not permitted
chown: /atlantis-data: Operation not permitted
chown: /atlantis-data: Operation not permitted
```

Works with helm chart 4.0.4 and ghcr.io/runatlantis/atlantis:v0.19.3

**Comment by tekumara** [comment]
See https://github.com/runatlantis/atlantis/issues/2322#issuecomment-1161400532

**Pull request merged**
