### PR TITLE
set additionalProperties to true

### PR DESCRIPTION
**Pull request by KyriosGN0**
## what

allow setting additional properties in the chart 

## why

we would like the ability to add additional properties to the chart 

## references
closes [#386](https://github.com/runatlantis/helm-charts/issues/386)

### CODE REVIEW

**Comment by KyriosGN0** [comment]
hi @GMartinez-Sisti, can i have some quick review on my PR? (if you would like a different approach, i can just add a enabled param in the schema file and have it be not required )

**Comment by GMartinez-Sisti** [comment]
> hi @GMartinez-Sisti, can i have some quick review on my PR? (if you would like a different approach, i can just add a enabled param in the schema file and have it be not required )

Hi @KyriosGN0, sorry for the late response! I was thinking about this PR this week and I feel that allowing extra values would invalidate having a schema file, the goal is exactly to prevent having users sending wrong configurations to the chart. Adding an enabled key doesn't make sense since it wouldn't do anything.

Looks like you have a similar setup as most places I've been, having enable and versions keys is common to control deploying an app, but we didn't add at the helm chart values level, we configured the values inside another key exactly to prevent situations like this:

Values file:

```yaml
atlantis:
  enabled: true
  version: 1.0.0
  helm:
    foo: bar
```

Argocd App:

```yaml
{{- if .Values.atlantis.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
spec:
  [...]
  source:
    chart: atlantis
    repoURL: https://runatlantis.github.io/helm-charts
    targetRevision: {{ .Values.atlantis.version }}
    helm:
      values: |
        {{- toYaml .Values.atlantis.helm | nindent 8 }}
{{- end }}
```

This way we don't have extra fields sent to the chart values.

While writing this I thought of another easy option, we can add an explicit `extra` config key to allow users to set  whatever they want, I think that having an explicit key for this doesn't invalidate the fact that we are strictly validating the other keys, since it's intentionally being used for that and not a possible mistake or typo.

Please let us know what you think of the options 😄

**Comment by KyriosGN0** [comment]
Thanks @GMartinez-Sisti for the review, we use a appset to create the apps so that's why we put a want to use atlantis.enabled to decide if to deploy the app at the destination cluster. 
so i think i the `extra` key is a the way to go, i'll open modify the PR in the coming days

**Comment by KyriosGN0** [comment]
after i took a look around the schema file i found i can use `global` instead of adding a new one
so closing this PR, Thanks!

**Pull request closed without merging**
