### PR TITLE
Add loadBalancerSourceRanges to schema

### PR DESCRIPTION
**Pull request by sviatlo**
## what

Add loadBalancerSourceRanges to schema

## why

The loadBalancerSourceRanges is an existing param in the chart, but passing it to the chart after the schema was added results in `- service: Additional property loadBalancerSourceRanges is not allowed` error.

## tests

Applied with passing the value and without passing the value.

### CODE REVIEW

**Comment by roytev** [comment]
@sviatlo Thanks! i missed it can you please also add it to the values so it will be noticed?

**Comment by jamengual** [comment]
@sviatlo can bump the char version to 4.17.2? thanks.

**Comment by sviatlo** [comment]
@roytev should I set it to null or empty array is good enough?

**Comment by roytev** [comment]
Hi @sviatlo Thanks it looks good!

**Review by roytev — APPROVED** [review]

**Comment by sviatlo** [comment]
@roytev @jamengual apologies for bugging you, but could someone please approve a CI run?

**Review by jamengual — APPROVED** [review]

**Comment by jamengual** [comment]
@sviatlo Thanks for the contribution!

**Pull request merged**
