### PR TITLE
Bump default app version to 0.24.2

### PR DESCRIPTION
**Pull request by jseiser**
## what

Bump App Version

## why

Default install should be latest stable release.

### CODE REVIEW

**Comment by jseiser** [comment]
just waiting on the Image to show up so i can test.

**Comment by nitrocode** [comment]
We may need to bump it one more time as there is still an outstanding issue related to policy.

We really need to fix the renovatebot here too to automatically bump this https://github.com/runatlantis/helm-charts/issues/295

**Comment by nitrocode** [comment]
No, let's keep this open. We may need to re-adjust this if we release 0.24.2 this week.

**Comment by jseiser** [comment]
@nitrocode 

I was able to test this out and it seems correct.

**Comment by jseiser** [comment]
@nitrocode 

Is this image going to be used, or will they be releasing a 0.24.2 and we should just wait?

**Comment by nitrocode** [comment]
There are still some issues. I'd wait.

See https://github.com/runatlantis/atlantis/pull/3461

**Comment by jseiser** [comment]
@nitrocode 

bumped to 0.24.2

**Pull request merged**
