### PR TITLE
Add ability to run Atlantis as a deployment

### PR DESCRIPTION
**Pull request by jacob-jameson**
## what

My team and I have added the ability to deploy Atlantis using a `deployment` controller rather than a `statefulSet`.  This also included adding the ability to create a seperate PVC for `atlantis-data`, which may help with [PR 304 - Move atlantis-data volume to a separate PVC](https://github.com/runatlantis/helm-charts/pull/304).

The type of controller used to deploy Atlantis is determined by a new setting `.Values.atlantisController` which has a default value of `statefulSet`. In the absence of this setting, a `statefulSet` controller will be created by default. This means that the changes are completely backwards compatible with the current default `values.yaml` file.

The `deployment` is configured through the `values.yaml` file in the `.Values.deployment` object.

In the event that the Atlantis cluster is scaled to zero and quickly scaled to one again, to prevent two pods from simultaneously trying to access the same lock and plan files we use `.Values.deployment.strategy: "Recreate"` by default.
## why

We use [KEDA](https://github.com/kedacore/keda) to scale our Kubernetes clusters based on events, but we would like the ability to scale our Atlantis clusters based on HTTPS events. To do this we need to use the KEDA [http-add-on](https://github.com/kedacore/http-add-on), which currently only supports `deployment` type controllers.

### Deployment
We tested these changes by deploying Atlantis with `deployment` and `statefulSet` controllers using the modified Helm chart in this request. Both are able to successfully deploy and pass the UI test suggested in the [README](https://github.com/runatlantis/helm-charts#testing-the-deployment) by running

```bash
helm test my-atlantis
```

### Scaling
When running Atlantis with a `deployment` controller, one of the main concerns is data in the PVC surviving pod failure. To confirm that data in the `atlantis-data` directory in the PVC does survive pod failure we;

1. Launched an interactive terminal in the Atlantis Pod
2. Created a text file in the `atlantis-data` directory
3. Exited the interactive terminal
4. Scale down the cluster to zero and Immediately scale back up to 1
5. Launched an interactive terminal in the new Atlantis Pod
6. Checked that the text file was still present in the`atlantis-data` directory

### Backwards Compatibility 
We also used the following command to test the Manifests produced.
```bash
helm install atlantis-release atlantis/ --values atlantis/values.yaml --dry-run --debug | tee manifests.txt
```
I ran this command in three scenarios:
1. Old Helm Chart, with old default values file 
1. New Helm Chart, with old default values file
1. New Helm Chart.  with new default values file (with default `statefulSet` controller)

In all of these scenarios the manifests produced were exactly the same. (Tested by comparing stringified YAML output)

## references

No references.

### CODE REVIEW

**Comment by jamengual** [comment]
thanks for the contribution @jacob-jameson , we will review shortly

**Comment by jacob-jameson** [comment]
The lint test failed because I forgot to bump the chart version number. What should I bump the version number to? Does this count as a Major/Minor/Patch update?

**Comment by jamengual** [comment]
since is not a breaking change let's update the minor version.

**Comment by jacob-jameson** [comment]
Could a Maintainer approve the Test Workflows pleas

**Review by GenPage — DISMISSED** [review]
LGTM, just need to dance around other pending approved PRs and bumping chart version

**Comment by jacob-jameson** [comment]
Is there anything I need to do pre-merge?

**Comment by jacob-jameson** [comment]
Is it acceptable to give a reviewer `write` permissions on my branch so that they can update the chart version when they review my code? I can't keep up with the chart version changes, and I have no idea when the linting pipelines will be run, so they always fail.

**Comment by jamengual** [comment]
no, you should wait until is reviewed and approved and then bump the chart version

**Comment by jacob-jameson** [comment]
I think all linting tests should pass now. Could I please get a code review?

**Comment by jacob-jameson** [comment]
Can I get a review please?

**Comment by cc-robertson** [comment]
we also have the same requirement. LGTM, can we get a review?

**Comment by jamengual** [comment]
@jacob-jameson could you fix the conflict? Thanks.

**Comment by jamengual** [comment]
@jacob-jameson please update the chart version please

**Comment by jamengual** [comment]
@jacob-jameson I bumped the version for you but now we have a JSON schema validation so please update the values there.

**Pull request closed without merging**
