### PR TITLE
feat: optionally allow to customize the terminationGracePeriodSeconds of the Statefull Set

### PR DESCRIPTION
**Pull request by tobwiens**
I would like to customize the terminationGracePeriodSeconds of the Statefull Set. 

Please find that config setting inside this PR.

- Updateded readme
- Updated values.yaml
- Added terminationGracePeriodSeconds as conditional, so that it can fall back to the Kubernetes default

Test:
- Tested it manually, deploying atlantis wits terraform helm_releease inside a GKE cluster. Works fine.

### CODE REVIEW

**Comment by tobwiens** [comment]
@mzupan @lkysow  I saw that you were reviewing some of the PRs. Just wanted to add that I have this forked the repo, deployed and tested it. Maybe that makes validating the PR easier. 

URL: [http://www.tobiaswiens.com/helm-charts/](url)

And here an example deployment:

```
resource "helm_release" "atlantis" {
  name              = "atlantis"
  repository        = "http://www.tobiaswiens.com/helm-charts/"
  chart             = "atlantis"



  values = [
    file("${path.module}/atlantis.yaml")
  ]

}
```

thank you ;)

Cheers,
Tobias

**Review by lkysow — APPROVED** [review]
LGTM, just needs a rebase

**Comment by Cylix** [comment]
@tobwiens Thanks for adding this, we are also looking forward to have this! 👍 

Since the PR is approved, do you have plans to rebase, or do you prefer someone to take over?

**Comment by lkysow** [comment]
> Since the PR is approved, do you have plans to rebase, or do you prefer someone to take over?

someone can take over

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @tobwiens for your contribution! Just released this as 3.19.0, let me know if that works, thanks!

**Pull request merged**
