### PR TITLE
Add support for multiple hosts in ingress

### PR DESCRIPTION
**Pull request by spirosoik**
This is a breaking change so we need to bump to a major release.

Removed old:
- `ingress.host`
- `ingress.path`

and introduced:
- `ingress.hosts`
- `ingress.hosts[0].paths`

Issue: https://github.com/runatlantis/helm-charts/issues/7

### CODE REVIEW

**Comment by lkysow** [comment]
Can we do this in a non-backwards breaking way? If `host` is not empty then use it, otherwise iterate through `hosts`.

**Comment by spirosoik** [comment]
hey @lkysow sure it's possible just it adds a bit more complexity and it could be odd in the sense that there is already the `hosts`. But it's definitely feasible

**Comment by spirosoik** [comment]
@lkysow have one more look. Right now we still support the old single host if it's set

**Comment by spirosoik** [comment]
@lkysow any update on this?

**Pull request merged**
