### PR TITLE
Feature: Add support for loadEnvFromConfigMaps

### PR DESCRIPTION
**Pull request by czerasz**

### CODE REVIEW

**Comment by czerasz** [comment]
Could someone help me fix the CI?

**Comment by lkysow** [comment]
> Could someone help me fix the CI?

You need to ensure the version in chart.yaml is bumped.

**Comment by czerasz** [comment]
@lkysow thx for the tip. CI passes :confetti_ball:

**Comment by czerasz** [comment]
@lkysow fine from Your side to merge this PR?

**Review by lkysow — APPROVED** [review]

**Pull request merged**
