### PR TITLE
feat(ingress): Allow creating secondary ingress

### LINKED ISSUE #282: Needs to have two seperate ingresses, one for the private interface, and one for "public" facing webhooks
The secure way to set up atlantis is to have two ingresses. One which is on the private network gives access to the web interface, which contains sensitive information and capabilities and needs restricted access.

The other should be used only for incoming webhooks, from github.com or similar things.

ArgoCD is set up this way. There's a applicationSet.webhook.ingress which is only for the ingress, and a server.ingress which is used for accessing the application.

With the current setup of the helm chart, someone is more likely to inadvertently expose their atlantis to the public.

### PR DESCRIPTION
**Pull request by jseiser**
## what

Allow creating a secondary ingress

## why

We want to be able to expose Atlantis to gitlab webhooks coming one network, while only allowing access to the Atlantis UI from our internal network/

## references
- closes #282

### CODE REVIEW

**Comment by jseiser** [comment]
I still need to test this, and im open to changing the naming/etc.  `secondary ingress` is what just came to mind.

**Comment by jseiser** [comment]
```
ingress:
  enabled: true
  ingressClassName: nginx
  host: atlantis.localdev.me
  path: /
secondary_ingress:
  enabled: true
  ingressClassName: nginx
  host: atlantis-webook.localdev.me
  path: /events
```


```
❯ kubectl get ingress -n atlantis
NAME                 CLASS   HOSTS                         ADDRESS   PORTS   AGE
atlantis-secondary   nginx   atlantis-webook.localdev.me             80      9s
atlantis             nginx   atlantis.localdev.me                    80      9s
```

```
❯ kubectl get ingress atlantis-secondary -n atlantis -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: atlantis
    meta.helm.sh/release-namespace: atlantis
  creationTimestamp: "2023-05-25T16:21:36Z"
  generation: 1
  labels:
    app: atlantis
    app.kubernetes.io/managed-by: Helm
    chart: atlantis-4.13.0
    helm.sh/chart: atlantis-4.13.0
    heritage: Helm
    release: atlantis
  name: atlantis-secondary
  namespace: atlantis
  resourceVersion: "85793"
  uid: 3ac3c770-2c3e-4f30-881a-c6244e2c49aa
spec:
  ingressClassName: nginx
  rules:
  - host: atlantis-webook.localdev.me
    http:
      paths:
      - backend:
          service:
            name: atlantis
            port:
              number: 80
        path: /events
        pathType: ImplementationSpecific
```


```
  ~/repos/helm-charts-2   dual_ingress *1 ?2                                                                                                                                                              ⎈ rancher-desktop  12:24:13 PM
❯ kubectl port-forward --namespace=ingress-nginx service/ingress-nginx-controller 8080:80
```

```
❯ curl -v atlantis-webook.localdev.me:8080/events
*   Trying 127.0.0.1:8080...
* Connected to atlantis-webook.localdev.me (127.0.0.1) port 8080 (#0)
> GET /events HTTP/1.1
> Host: atlantis-webook.localdev.me:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< Date: Thu, 25 May 2023 16:36:15 GMT
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host atlantis-webook.localdev.me left intact
```

```
127.0.0.1 - - [25/May/2023:16:36:15 +0000] "GET /events HTTP/1.1" 405 0 "-" "curl/7.81.0" 102 0.000 [atlantis-atlantis-80] [] 10.42.0.140:4141 0 0.001 405 f0c1859440692e6bbdfc127e443eda16
```

**Comment by jseiser** [comment]
Then as a post, we see it gets to atlantis

```
❯ curl -v -X POST atlantis-webook.localdev.me:8080/events
```

```
{"level":"debug","ts":"2023-05-25T16:43:07.708Z","caller":"server/middleware.go:45","msg":"POST /events – from 10.42.0.138:59350","json":{}}
{"level":"debug","ts":"2023-05-25T16:43:07.708Z","caller":"logging/simple_logger.go:157","msg":"Ignoring request","json":{}}
{"level":"debug","ts":"2023-05-25T16:43:07.708Z","caller":"server/middleware.go:72","msg":"POST /events – respond HTTP 400","json":{}}
```

**Comment by jseiser** [comment]
@nitrocode 
@jamengual 

I believe this is good to go.  Im not sure how you guys would want to vet this, or discuss this.

**Comment by GenPage** [comment]
> I still need to test this, and im open to changing the naming/etc. `secondary ingress` is what just came to mind.

Could we do "webhook" ingress or "internal/external"?

**Comment by jseiser** [comment]
@GenPage 

updated to `webhook_ingress`

**Comment by jseiser** [comment]
fixed linting

**Comment by jseiser** [comment]
@GenPage 

Im not sure what this current failure is.

**Comment by jseiser** [comment]
@GenPage 

Not sure what needs to happen to make this bats stuff work.

**Comment by paul-civitas** [comment]
@jseiser 

> Normal BackOff 4m50s (x20 over 9m55s) kubelet Back-off pulling image "bats/bats:v1.9.0"

Looks like you're using a image from dockerhub. Docker hub has a lot of issues regarding rate limiting and many other things. You want to avoid using any images from dockerhub these days.

Also it seems the bats image was removed from dockerhub. https://hub.docker.com/r/bats/bats

**Comment by GMartinez-Sisti** [comment]
@jseiser WDYT of duplicating the ci values file ([ci-values.yaml](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/ci/ci-values.yaml)) and append the new config so we could test it on the ci too?

**Comment by jseiser** [comment]
The more testing the better, but without an Ingress Controller in this testing cluster is it going to do anything?

**Comment by GMartinez-Sisti** [comment]
> The more testing the better, but without an Ingress Controller in this testing cluster is it going to do anything?

Nothing will use the ingress but it will still create the resource. In this case it's more of a templating test.

**Review by jamengual — APPROVED** [review]

**Comment by jamengual** [comment]
Thanks @jseiser for the contribution

**Comment by kzap** [comment]
Could we add this to the README docs?

**Comment by jamengual** [comment]
@kzap if you want to create a PR to add that to the readme as an example that will be cool.
We will be happy to review it.

**Comment by glasser** [comment]
Docs would definitely be appreciated. It was not obvious to me that there's nothing "special" about the webhook ingress that means it only exposes the `/events` path unless you're sure to configure it that way in your values file!

**Pull request merged**
